// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include "cache.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCache final : ::djinni::JniInterface<::smobiler::Cache, NativeCache> {
public:
    using CppType = std::shared_ptr<::smobiler::Cache>;
    using CppOptType = std::shared_ptr<::smobiler::Cache>;
    using JniType = jobject;

    using Boxed = NativeCache;

    ~NativeCache();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCache>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCache>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCache();
    friend ::djinni::JniClass<NativeCache>;
    friend ::djinni::JniInterface<::smobiler::Cache, NativeCache>;

};

}  // namespace djinni_generated
