// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#include "NativeAsyncTask.hpp"  // my header

namespace djinni_generated {

NativeAsyncTask::NativeAsyncTask() : ::djinni::JniInterface<::smobiler::AsyncTask, NativeAsyncTask>("com/smobiler/djinni/AsyncTask$CppProxy") {}

NativeAsyncTask::~NativeAsyncTask() = default;


CJNIEXPORT void JNICALL Java_com_smobiler_djinni_AsyncTask_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::smobiler::AsyncTask>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_smobiler_djinni_AsyncTask_00024CppProxy_native_1execute(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::smobiler::AsyncTask>(nativeRef);
        ref->execute();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
