// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#include "NativeUtils.hpp"  // my header
#include "NativeUtilsInterface.hpp"

namespace djinni_generated {

NativeUtils::NativeUtils() : ::djinni::JniInterface<::smobiler::Utils, NativeUtils>("com/smobiler/djinni/Utils$CppProxy") {}

NativeUtils::~NativeUtils() = default;


CJNIEXPORT void JNICALL Java_com_smobiler_djinni_Utils_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::smobiler::Utils>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_smobiler_djinni_Utils_create(JNIEnv* jniEnv, jobject /*this*/, jobject j_interface)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        ::smobiler::Utils::create(::djinni_generated::NativeUtilsInterface::toCpp(jniEnv, j_interface));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
