// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#include "NativeLog.hpp"  // my header
#include "NativeLogInterface.hpp"

namespace djinni_generated {

NativeLog::NativeLog() : ::djinni::JniInterface<::smobiler::Log, NativeLog>("com/smobiler/djinni/Log$CppProxy") {}

NativeLog::~NativeLog() = default;


CJNIEXPORT void JNICALL Java_com_smobiler_djinni_Log_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::smobiler::Log>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_smobiler_djinni_Log_create(JNIEnv* jniEnv, jobject /*this*/, jobject j_l)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        ::smobiler::Log::create(::djinni_generated::NativeLogInterface::toCpp(jniEnv, j_l));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
