// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include "djinni_support.hpp"
#include "log.hpp"

namespace djinni_generated {

class NativeLog final : ::djinni::JniInterface<::smobiler::Log, NativeLog> {
public:
    using CppType = std::shared_ptr<::smobiler::Log>;
    using CppOptType = std::shared_ptr<::smobiler::Log>;
    using JniType = jobject;

    using Boxed = NativeLog;

    ~NativeLog();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLog>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLog>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLog();
    friend ::djinni::JniClass<NativeLog>;
    friend ::djinni::JniInterface<::smobiler::Log, NativeLog>;

};

}  // namespace djinni_generated
