// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include "djinni_support.hpp"
#include "stml.hpp"

namespace djinni_generated {

class NativeStml final : ::djinni::JniInterface<::smobiler::Stml, NativeStml> {
public:
    using CppType = std::shared_ptr<::smobiler::Stml>;
    using CppOptType = std::shared_ptr<::smobiler::Stml>;
    using JniType = jobject;

    using Boxed = NativeStml;

    ~NativeStml();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeStml>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeStml>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeStml();
    friend ::djinni::JniClass<NativeStml>;
    friend ::djinni::JniInterface<::smobiler::Stml, NativeStml>;

};

}  // namespace djinni_generated
