// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#include "NativeUtilsInterface.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeUtilsInterface::NativeUtilsInterface() : ::djinni::JniInterface<::smobiler::UtilsInterface, NativeUtilsInterface>() {}

NativeUtilsInterface::~NativeUtilsInterface() = default;

NativeUtilsInterface::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeUtilsInterface::JavaProxy::~JavaProxy() = default;

std::string NativeUtilsInterface::JavaProxy::getRootPath() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeUtilsInterface>::get();
    auto jret = (jstring)jniEnv->CallObjectMethod(Handle::get().get(), data.method_getRootPath);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::String::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
