// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include "djinni_support.hpp"
#include "utils.hpp"

namespace djinni_generated {

class NativeUtils final : ::djinni::JniInterface<::smobiler::Utils, NativeUtils> {
public:
    using CppType = std::shared_ptr<::smobiler::Utils>;
    using CppOptType = std::shared_ptr<::smobiler::Utils>;
    using JniType = jobject;

    using Boxed = NativeUtils;

    ~NativeUtils();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeUtils>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeUtils>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeUtils();
    friend ::djinni::JniClass<NativeUtils>;
    friend ::djinni::JniInterface<::smobiler::Utils, NativeUtils>;

};

}  // namespace djinni_generated
