// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

package com.smobiler.djinni;

/** log */
public abstract class LogInterface {
    public abstract void d(String tag, String msg);

    public abstract void w(String tag, String msg);

    public abstract void e(String tag, String msg);

    public abstract void i(String tag, String msg);
}
