// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

package com.smobiler.djinni;

public abstract class StmlListener {
    public abstract void connecting();

    public abstract void connected();

    public abstract void disconnect(String error);

    public abstract void received(String msg);

    public abstract void sended(String msg);

    public abstract void sending(String msg, boolean showloading);
}
