// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from thread.djinni

package com.smobiler.djinni;

public abstract class ThreadLauncher {
    /** name is nullable */
    public abstract void startThread(String name, AsyncTask runFn);
}
