// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

package com.smobiler.djinni;

/** utils */
public abstract class UtilsInterface {
    /** 获取应用可读写的目录 */
    public abstract String getRootPath();
}
