// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#import <Foundation/Foundation.h>


/** cache */
@interface SMCache : NSObject

- (nonnull NSString *)get:(nonnull NSString *)key
              defaultVaue:(nonnull NSString *)defaultVaue;

- (BOOL)find:(nonnull NSString *)key;

- (BOOL)del:(nonnull NSString *)key;

- (BOOL)put:(nonnull NSString *)key
      value:(nonnull NSString *)value;

- (nonnull NSString *)getRootPath;

@end
