// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#import <Foundation/Foundation.h>
@class SMAsyncTask;


@protocol SMEventLoop

- (void)post:(nullable SMAsyncTask *)task;

@end
