// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#include "event_loop.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol SMEventLoop;

namespace djinni_generated {

class EventLoop
{
public:
    using CppType = std::shared_ptr<::smobiler::EventLoop>;
    using CppOptType = std::shared_ptr<::smobiler::EventLoop>;
    using ObjcType = id<SMEventLoop>;

    using Boxed = EventLoop;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

