// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#include "log.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SMLog;

namespace djinni_generated {

class Log
{
public:
    using CppType = std::shared_ptr<::smobiler::Log>;
    using CppOptType = std::shared_ptr<::smobiler::Log>;
    using ObjcType = SMLog*;

    using Boxed = Log;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

