// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#import <Foundation/Foundation.h>
@protocol SMLogInterface;


@interface SMLog : NSObject

+ (void)create:(nullable id<SMLogInterface>)l;

@end
