// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#import "SMLog+Private.h"
#import "SMLog.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "SMLogInterface+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SMLog ()

- (id)initWithCpp:(const std::shared_ptr<::smobiler::Log>&)cppRef;

@end

@implementation SMLog {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::smobiler::Log>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::smobiler::Log>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (void)create:(nullable id<SMLogInterface>)l {
    try {
        ::smobiler::Log::create(::djinni_generated::LogInterface::toCpp(l));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Log::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Log::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SMLog>(cpp);
}

}  // namespace djinni_generated

@end
