// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#import <Foundation/Foundation.h>


@protocol SMStmlListener

- (void)connecting;

- (void)connected;

- (void)disconnect:(nonnull NSString *)error;

- (void)received:(nonnull NSString *)msg;

- (void)sended:(nonnull NSString *)msg;

- (void)sending:(nonnull NSString *)msg
    showloading:(BOOL)showloading;

@end
