// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#include "stml.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SMStml;

namespace djinni_generated {

class Stml
{
public:
    using CppType = std::shared_ptr<::smobiler::Stml>;
    using CppOptType = std::shared_ptr<::smobiler::Stml>;
    using ObjcType = SMStml*;

    using Boxed = Stml;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

