// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#import <Foundation/Foundation.h>
@class SMStml;
@protocol SMStmlListener;


/** stml */
@interface SMStml : NSObject

- (void)start:(nonnull NSString *)server
         port:(int32_t)port;

- (void)setKeeplive:(BOOL)alive;

- (void)setTimeout:(int32_t)timeout;

- (void)forceReconnect;

- (void)post:(nonnull NSString *)msg
 showloading:(BOOL)showloading;

- (void)bye;

- (void)setListener:(nullable id<SMStmlListener>)listener;

+ (nullable SMStml *)create;

@end
