// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#include "stml_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol SMStmlListener;

namespace djinni_generated {

class StmlListener
{
public:
    using CppType = std::shared_ptr<::smobiler::StmlListener>;
    using CppOptType = std::shared_ptr<::smobiler::StmlListener>;
    using ObjcType = id<SMStmlListener>;

    using Boxed = StmlListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

