// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#import <Foundation/Foundation.h>


/** utils */
@protocol SMUtilsInterface

/** 获取应用可读写的目录 */
- (nonnull NSString *)getRootPath;

@end
