// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#import "SMUtils+Private.h"
#import "SMUtils.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "SMUtilsInterface+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SMUtils ()

- (id)initWithCpp:(const std::shared_ptr<::smobiler::Utils>&)cppRef;

@end

@implementation SMUtils {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::smobiler::Utils>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::smobiler::Utils>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (void)create:(nullable id<SMUtilsInterface>)interface {
    try {
        ::smobiler::Utils::create(::djinni_generated::UtilsInterface::toCpp(interface));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Utils::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Utils::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SMUtils>(cpp);
}

}  // namespace djinni_generated

@end
