// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#import <Foundation/Foundation.h>
@protocol SMUtilsInterface;


@interface SMUtils : NSObject

+ (void)create:(nullable id<SMUtilsInterface>)interface;

@end
