// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#include "utils.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SMUtils;

namespace djinni_generated {

class Utils
{
public:
    using CppType = std::shared_ptr<::smobiler::Utils>;
    using CppOptType = std::shared_ptr<::smobiler::Utils>;
    using ObjcType = SMUtils*;

    using Boxed = Utils;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

