// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#include "utils_interface.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol SMUtilsInterface;

namespace djinni_generated {

class UtilsInterface
{
public:
    using CppType = std::shared_ptr<::smobiler::UtilsInterface>;
    using CppOptType = std::shared_ptr<::smobiler::UtilsInterface>;
    using ObjcType = id<SMUtilsInterface>;

    using Boxed = UtilsInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

