// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#pragma once

namespace smobiler {

class AsyncTask {
public:
    virtual ~AsyncTask() {}

    virtual void execute() = 0;
};

}  // namespace smobiler
