// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include <string>

namespace smobiler {

/** cache */
class Cache {
public:
    virtual ~Cache() {}

    virtual std::string get(const std::string & key, const std::string & defaultVaue) = 0;

    virtual bool find(const std::string & key) = 0;

    virtual bool del(const std::string & key) = 0;

    virtual bool put(const std::string & key, const std::string & value) = 0;

    virtual std::string getRootPath() = 0;
};

}  // namespace smobiler
