// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include <memory>

namespace smobiler {

class LogInterface;

class Log {
public:
    virtual ~Log() {}

    static void create(const std::shared_ptr<LogInterface> & l);
};

}  // namespace smobiler
