// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include <string>

namespace smobiler {

/** log */
class LogInterface {
public:
    virtual ~LogInterface() {}

    virtual void d(const std::string & tag, const std::string & msg) = 0;

    virtual void w(const std::string & tag, const std::string & msg) = 0;

    virtual void e(const std::string & tag, const std::string & msg) = 0;

    virtual void i(const std::string & tag, const std::string & msg) = 0;
};

}  // namespace smobiler
