// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include <string>

namespace smobiler {

class StmlListener {
public:
    virtual ~StmlListener() {}

    virtual void connecting() = 0;

    virtual void connected() = 0;

    virtual void disconnect(const std::string & error) = 0;

    virtual void received(const std::string & msg) = 0;

    virtual void sended(const std::string & msg) = 0;

    virtual void sending(const std::string & msg, bool showloading) = 0;
};

}  // namespace smobiler
