// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace smobiler {

class StmlListener;

/** stml */
class Stml {
public:
    virtual ~Stml() {}

    virtual void start(const std::string & server, int32_t port) = 0;

    virtual void setKeeplive(bool alive) = 0;

    virtual void forceReconnect() = 0;

    virtual void post(const std::string & msg, bool showloading) = 0;

    virtual void bye() = 0;

    virtual void setListener(const std::shared_ptr<StmlListener> & listener) = 0;

    static std::shared_ptr<Stml> create();
};

}  // namespace smobiler
