// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include <string>

namespace smobiler {

/** utils */
class UtilsInterface {
public:
    virtual ~UtilsInterface() {}

    /** 获取应用可读写的目录 */
    virtual std::string getRootPath() = 0;
};

}  // namespace smobiler
