// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stml.djinni

#pragma once

#include <memory>

namespace smobiler {

class UtilsInterface;

class Utils {
public:
    virtual ~Utils() {}

    static void create(const std::shared_ptr<UtilsInterface> & interface);
};

}  // namespace smobiler
